name: Debian Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  build-push:
    name: Docker-Image erstellen und in die GitHub-Containerregistrierung übertragen
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Auschecken des Repositorys
      uses: actions/checkout@v2

    - name: Anmelden in der GitHub Container-Registrierung
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Letzten Release abfragen
      id: last_release
      uses: dave-ohouse/action-latest-release-info@v1.3.0
      env:
       GITHUB_TOKEN: ${{ github.token }}

    - name: Erstellen und übertragen des Docker-Images
      env:
        REGISTRY: ${{ env.REGISTRY }}
        OWNER: ${{ github.repository_owner }}
        IMAGE_NAME: pbx-debian
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/pbx-debian:${{ steps.last_release.outputs.name }}, ghcr.io/${{ github.repository_owner }}/pbx-debian:latest
        build-args: |
          ENVIRONMENT=production
